# Generated by Django 5.1.6 on 2025-02-18 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('params', models.CharField(max_length=255, null=True)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DBResponseAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('object_id', models.IntegerField()),
                ('content', models.JSONField(null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_responses', to='audit_log.auditlog')),
            ],
            options={
                'verbose_name_plural': 'DB Responses',
            },
        ),
    ]
